count: 120
max-sizex: 3
max-sizey: 4
classes:
    note:
      items:
        markdown:
          ids:
            - 3487238764
            - 2394763274
            - 23746328746
    foursquare:
      items:
        place:
          ids:
            - 3487238764
            - 2394763274
            - 23746328746
    goodreads:
      items:
        book:
          content:
            - >
              https://www.goodreads.com/book/show/375802?format=xml&key=gyMvEx2C09xhl3jnfAlA
      items:
        document:
          ids:
            - 3487238764
            - 2394763274
            - 23746328746
    google_maps:
      items:
        place:
          ids:
            - 3487238764
            - 2394763274
            - 23746328746
    instagram:
      items:
        photo:
          content:
            - >
              {"provider_url":"https:\/\/instagram.com\/","media_id":"1097373296066626766_4810832","author_name":"teamcoco","height":null,"thumbnail_url":"https:\/\/scontent-lga3-1.cdninstagram.com\/hphotos-xaf1\/t51.2885-15\/e35\/12132825_873825346046997_607706172_n.jpg","thumbnail_width":640,"thumbnail_height":427,"provider_name":"Instagram","title":"#CONAN. #Beard. #Smokingjacket. #fbf","html":"\u003cblockquote class=\"instagram-media\" data-instgrm-captioned data-instgrm-version=\"5\" style=\" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);\"\u003e\u003cdiv style=\"padding:8px;\"\u003e \u003cdiv style=\" background:#F8F8F8; line-height:0; margin-top:40px; padding:33.359375% 0; text-align:center; width:100%;\"\u003e \u003cdiv style=\" background:url(data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf\/\/42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB\/lQPb79drWOyJVa\/DAvg9B\/rLB4cC+Nqgdz\/TvBbBnr6GBReqn\/nRmDgaQEej7WhonozjF+Y2I\/fZou\/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;\"\u003e\u003c\/div\u003e\u003c\/div\u003e \u003cp style=\" margin:8px 0 0 0; padding:0 4px;\"\u003e \u003ca href=\"https:\/\/instagram.com\/p\/86pzLaDQTO\/\" style=\" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;\" target=\"_blank\"\u003e#CONAN. #Beard. #Smokingjacket. #fbf\u003c\/a\u003e\u003c\/p\u003e \u003cp style=\" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;\"\u003eA photo posted by CONAN on TBS (@teamcoco) on \u003ctime style=\" font-family:Arial,sans-serif; font-size:14px; line-height:17px;\" datetime=\"2015-10-16T23:11:52+00:00\"\u003eOct 16, 2015 at 4:11pm PDT\u003c\/time\u003e\u003c\/p\u003e\u003c\/div\u003e\u003c\/blockquote\u003e\n\u003cscript async defer src=\"\/\/platform.instagram.com\/en_US\/embeds.js\"\u003e\u003c\/script\u003e","width":658,"version":"1.0","author_url":"https:\/\/instagram.com\/teamcoco","author_id":4810832,"type":"rich"}
        video:
          content:
            - >
              {"provider_url":"https:\/\/instagram.com\/","media_id":"1095875700197791851_31264453","author_name":"dethbird","height":null,"thumbnail_url":"https:\/\/scontent-lga3-1.cdninstagram.com\/hphotos-xfa1\/t51.2885-15\/e15\/12145322_1053120074728637_1866237520_n.jpg","thumbnail_width":640,"thumbnail_height":640,"provider_name":"Instagram","title":"","html":"\u003cblockquote class=\"instagram-media\" data-instgrm-version=\"5\" style=\" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);\"\u003e\u003cdiv style=\"padding:8px;\"\u003e \u003cdiv style=\" background:#F8F8F8; line-height:0; margin-top:40px; padding:50.0% 0; text-align:center; width:100%;\"\u003e \u003cdiv style=\" background:url(data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf\/\/42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB\/lQPb79drWOyJVa\/DAvg9B\/rLB4cC+Nqgdz\/TvBbBnr6GBReqn\/nRmDgaQEej7WhonozjF+Y2I\/fZou\/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;\"\u003e\u003c\/div\u003e\u003c\/div\u003e\u003cp style=\" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;\"\u003e\u003ca href=\"https:\/\/instagram.com\/p\/81VSSkRZhr\/\" style=\" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;\" target=\"_blank\"\u003eA video posted by Dethbird (@dethbird)\u003c\/a\u003e on \u003ctime style=\" font-family:Arial,sans-serif; font-size:14px; line-height:17px;\" datetime=\"2015-10-14T21:36:25+00:00\"\u003eOct 14, 2015 at 2:36pm PDT\u003c\/time\u003e\u003c\/p\u003e\u003c\/div\u003e\u003c\/blockquote\u003e\n\u003cscript async defer src=\"\/\/platform.instagram.com\/en_US\/embeds.js\"\u003e\u003c\/script\u003e","width":658,"version":"1.0","author_url":"https:\/\/instagram.com\/dethbird","author_id":31264453,"type":"rich"}
    spotify:
      items:
        track:
          content:
            - >
              {"album":{"album_type":"album","external_urls":{"spotify":"https://open.spotify.com/album/6TJmQnO44YE5BtTxH8pop1"},"href":"https://api.spotify.com/v1/albums/6TJmQnO44YE5BtTxH8pop1","id":"6TJmQnO44YE5BtTxH8pop1","images":[{"height":640,"url":"https://d3rt1990lpmkn.cloudfront.net/original/8e13218039f81b000553e25522a7f0d7a0600f2e","width":629},{"height":300,"url":"https://d3rt1990lpmkn.cloudfront.net/original/8c1e066b5d1045038437d92815d49987f519e44f","width":295},{"height":64,"url":"https://d3rt1990lpmkn.cloudfront.net/original/d49268a8fc0768084f4750cf1647709e89a27172","width":63}],"name":"Hot Fuss","type":"album","uri":"spotify:album:6TJmQnO44YE5BtTxH8pop1"},"artists":[{"external_urls":{"spotify":"https://open.spotify.com/artist/0C0XlULifJtAgn6ZNCW2eu"},"href":"https://api.spotify.com/v1/artists/0C0XlULifJtAgn6ZNCW2eu","id":"0C0XlULifJtAgn6ZNCW2eu","name":"The Killers","type":"artist","uri":"spotify:artist:0C0XlULifJtAgn6ZNCW2eu"}],"available_markets":["AD","AR","T","W","UY"],"disc_number":1,"duration_ms":222075,"explicit":false,"external_ids":{"isrc":"USIR20400274"},"external_urls":{"spotify":"https://open.spotify.com/track/0eGsygTp906u18L0Oimnem"},"href":"https://api.spotify.com/v1/tracks/0eGsygTp906u18L0Oimnem","id":"0eGsygTp906u18L0Oimnem","name":"Mr. Brightside","popularity":0,"preview_url":"http://d318706lgtcm8e.cloudfront.net/mp3-preview/f454c8224828e21fa146af84916fd22cb89cedc6","track_number":2,"type":"track","uri":"spotify:track:0eGsygTp906u18L0Oimnem"}
    trello:
      items:
        board:
          ids:
            - 3487238764
            - 2394763274
            - 23746328746
    twitter:
      items:
        tweet:
          content:
            - "175800300060409856"
            - "180488009832079361"
            - "178887690022952960"
    youtube:
      items:
        video:
          content:
            - >
              {"kind":"youtube#video","etag":"\"fpJ9onbY0Rl_LqYLG6rOCJ9h9N8/3StQIcXdtBodZj8Ewtm4Phh4NVQ\"","id":"e7WcjUUntpE","snippet":{"publishedAt":"2014-11-04T15:20:02.000Z","channelId":"UCEd3MIV2qw8B4M7g1HxPrEg","title":"Conan's Goodbye Speech on \"Late Night with Conan O'Brien\" 2/20/09","description":"Conan's final speech before moving out to Los Angeles to do the Tonight Show.","thumbnails":{"default":{"url":"https://i.ytimg.com/vi/e7WcjUUntpE/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/e7WcjUUntpE/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/e7WcjUUntpE/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/e7WcjUUntpE/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/e7WcjUUntpE/maxresdefault.jpg","width":1280,"height":720}},"channelTitle":"Conan Tonight Show","tags":["Late Night With Conan O'Brien (TV Program)","Conan O'Brien (Celebrity)","Talk Show (TV Genre)","The Tonight Show With Conan O'Brien (TV Program)"],"categoryId":"23","liveBroadcastContent":"none","localized":{"title":"Conan's Goodbye Speech on \"Late Night with Conan O'Brien\" 2/20/09","description":"Conan's final speech before moving out to Los Angeles to do the Tonight Show."}}}
    wordpress:
      items:
        post:
          ids:
            - 3487238764
            - 2394763274
            - 23746328746
